### PR TITLE
Add Exim4 role

### PR DESCRIPTION
**Pull request by joequery**
This PR adds the Exim4 Mail Transfer Agent. Currently the only exim configuration available is `amazon_ses`.

## Testing

Make the following adjustments to the `roles/exim/defaults/main.yml` file:

1. Change `exim_mailname` to the proper domain (`istresearch.com` for IST employees)
2. Alter the `username` and `password` for the `exim_amazon_ses_conf`. (IST employees can find SES credentials in LastPass)
3. Change
        
        exim_configs: []
        # - "{{ exim_amazon_ses_conf.conf_name }}"

to

    exim_configs:
      - "{{ exim_amazon_ses_conf.conf_name }}"

Run the exim role:

    $ ansible-playbook -v -i staging.inventory -u vagrant --limit=vagrant-as-01 --tags="site-exim" site-infrastructure.yml

SSH into `vagrant-as-01` and send yourself an email using the following command:

    (vagrant-as-01)$ echo "This is a test." | mail -v -s TheSubject your_email@gmail.com

The command should have the following as the last lines in the output:

```
LOG: MAIN
  Completed
```

You should also have received the email in your inbox.

### CODE REVIEW

**Comment by deecav** [comment]
I get this at the end when trying to send the email

`LOG: MAIN
  ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [50.19.94.229] Connection timed out`

**Comment by deecav** [comment]
I have the username and password from LastPass entered correctly and I following all instructions (double and triple checked)

**Comment by deecav** [comment]
Here is the exim4 log file contents

`2016-11-07 18:32:22 exim 4.82 daemon started: pid=6202, -q30m, listening for SMTP on [127.0.0.1]:25 [::1]:25
2016-11-07 18:32:22 Start queue run: pid=6203
2016-11-07 18:32:22 End queue run: pid=6203
2016-11-07 18:32:25 pid 6202: SIGHUP received: re-exec daemon
2016-11-07 18:32:25 exim 4.82 daemon started: pid=6202, -q30m, listening for SMTP on [127.0.0.1]:25 [::1]:25
2016-11-07 18:32:25 Start queue run: pid=7094
2016-11-07 18:32:25 End queue run: pid=7094
2016-11-07 18:34:44 1c3okm-0004JY-VI <= vagrant@istresearch.com U=vagrant P=local S=511
2016-11-07 18:36:23 1c3omN-0004Jg-Dy <= vagrant@istresearch.com U=vagrant P=local S=491
2016-11-07 18:36:52 1c3okm-0004JY-VI ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [184.73.218.26] Connection timed out
2016-11-07 18:38:30 1c3omN-0004Jg-Dy ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [50.19.94.229] Connection timed out
2016-11-07 18:38:59 1c3okm-0004JY-VI ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [174.129.24.188] Connection timed out
2016-11-07 18:40:37 1c3omN-0004Jg-Dy ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [174.129.35.96] Connection timed out
2016-11-07 18:41:06 1c3okm-0004JY-VI ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [54.243.225.221] Connection timed out
2016-11-07 18:42:45 1c3omN-0004Jg-Dy ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [54.235.77.145] Connection timed out
2016-11-07 18:43:14 1c3okm-0004JY-VI ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [174.129.224.137] Connection timed out
2016-11-07 18:44:52 1c3omN-0004Jg-Dy ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [23.21.91.54] Connection timed out
2016-11-07 18:45:21 1c3okm-0004JY-VI ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [54.243.47.187] Connection timed out
2016-11-07 18:45:21 1c3okm-0004JY-VI == david.cavitt@istresearch.com R=send_via_ses T=ses_smtp defer (110): Connection timed out
2016-11-07 18:46:59 1c3omN-0004Jg-Dy ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com [107.21.244.69] Connection timed out
2016-11-07 18:46:59 1c3omN-0004Jg-Dy == dmcavitt@gmail.com R=send_via_ses T=ses_smtp defer (110): Connection timed out
2016-11-07 20:03:40 exim 4.82 daemon started: pid=1461, -q30m, listening for SMTP on [127.0.0.1]:25 [::1]:25`

**Comment by deecav** [comment]
Changing ports to 587 worked like a charm!

`LOG: MAIN
  Completed`

**Comment by joequery** [comment]
Build passed, merging.

**Pull request merged**
