### PR TITLE
Using SIGTERM instead of SIGKILL

### PR DESCRIPTION
**Pull request by andrewkcarter**
**Important notes about deploying these changes!** 
If we run Ansible to deploy these changes we're going to put our stuff through another round of kill -9 shutdowns which is harmful and extremely risky especially when you consider that Ansible will restart the cluster all at once.

These are the steps that I suggest:
1. Manually edit the supervisor.d config file for that process.
2. Run supervisorctl reread _service_
3. Monitor the logs for the service with tail -f _log-file_
4. Manually start a clean shutdown by running kill _pid_ on the service
5. When the process exits, supervisord will immediately start it again but still with the old config. As soon as you witness the process starting (within seconds) immediately execute supervisorctl update _service_. Supervisord will kill -9 it (before it has really started to handle data) and then start it again with the new config.

I tested this process on a VM and it work well for Kafka. The next time we do run Ansible everything will execute normal shutdowns in a safe manner.

### CODE REVIEW

**Comment by joequery** [comment]
Some reading in case we come across issues with processes hanging around by attempting graceful shutdowns: https://coderwall.com/p/4tcw7w/setting-supervisor-to-really-stop-django-runserver

**Comment by andrewkcarter** [comment]
Yes there may be specific processes that need tailored shutdown execution.

**Comment by andrewkcarter** [comment]
What probably happened here is that one config was written using KILL, and then copy/pasted to create the rest. Who knows, maybe this is carry over from ILD/WAT in which case I'm the most likely perpetrator.  However it happened to be, it needs to be corrected.

**Comment by andrewkcarter** [comment]
**Important notes about deploying these changes!** 
If we run Ansible to deploy these changes we're going to put our stuff through another round of kill -9 shutdowns which is harmful and extremely risky especially when you consider that Ansible will restart the cluster all at once.

These are the steps that I suggest:
1. Manually edit the supervisor.d config file for that process.
2. Run `supervisorctl reread <service>`
3. Monitor the logs for the service with `tail -f <log-file>`
4. Manually start a clean shutdown by running `kill <pid>` on the service
5. When the process exits, supervisord will immediately start it again but with the old config. As soon as you witness the process starting (within seconds) immediately execute `supervisorctl reload <service>`. Suupervisord will `kill -9` it (before it has really started to handle data) and then start it again with the new config.

I tested this process on a VM and it work well for Kafka.

**Comment by madisonb** [comment]
Why did you opt for 600 seconds to shut down? do some processes really take that long? I think we should test to make sure all of these changes actually will work on each process vs blanket changing them all.

**Comment by joequery** [comment]
Note: supervisord will automatically attempt a SIGKILL if the previous kill signal was unsuccessful after a period of time: https://github.com/Supervisor/supervisor/blob/154cb4c84f28ac3e0ac1ce5409faea65c15d2d02/supervisor/process.py#L642-L651

So SIGKILL should only ever specified in the configs here if there's a really, really good reason to do that first without attempting any other kill signal.

**Comment by andrewkcarter** [comment]
Six hundred seconds is arbitrary. Clean shutdown of Kafka and Hbase Region Servers involves transferring ownership of data to other players and completing WAL work. As soon as the process ends, supervisor moves on. It doesn't wait 10 minutes to return from the 'stop' command. This just means we have a 10 minutes window before supervisor -9's it. Which should be avoided in almost every normal case.

Our current kafka brokers actually take about a minute to do a real shutdown, but you wouldn't know it because we've just been killing them. And startup is waaay faster because the broker isn't trying to recover the corrupt partition logs from the WAL and then reconcile current state with other brokers due to being terminated.

**Comment by andrewkcarter** [comment]
Yes I agree this need to be tested and validated for each process. I will if I have some time next sprint.

**Comment by joequery** [comment]
@andrewkcarter Is there a way I can help with testing this?

**Comment by andrewkcarter** [comment]
I'll submit these as individual PRs that can be easily verified.

**Pull request closed without merging**
